### ISSUE TITLE
Repairing a broken ship spawns rewards in infinite loop

### ISSUE THREAD

**Issue by draganczukp** [Rikiki123456789/Rimworld#11]
I just finished repairing a "damaged ship" from an event and it keeps spawning rewards (packaged survival meals, gold and plasteel) in an infinite loop.

Here is a video of that: [https://youtu.be/11lZde1aX8E](video)

Also a screenshot of debug console: [https://imgur.com/YweM3wL](img)

Platform: Arch Linux, Steam
Rimworld version b18
Mod installed with steam workshop

**Comment by Rikiki123456789** [comment]
Hi draganczukp!

Sorry for the late repsonse, I was quite busy lately.

Questions:
* Did you added the mod mid-game? It seems that the MingCo. faction is null.
* Is the MiningCo. mining helmet mod enabled?
* Can you share your mod list, please?

The mod will be updated for V1.0 so please have another try (you can use dev mode to fasten test) and let me know if you still get this bug.

Cheers,
Rikiki

**Comment by draganczukp** [comment]
- I did add it mid-game. I thought it was safe to add to existing saves.
- When that happened I didn't know about other MiningCo. mods
- It's been a while and my mod list has changed significantly (I switched to b19, added more mods, removed some I didn't want anymore etc.)

**Comment by Rikiki123456789** [comment]
Okay, so it is just that you need a fresh colony or Orion's "Faction discovery" mod.
Keep it in mind for V1.0. :-)
