### ISSUE TITLE
ForceField not working as intended with CR

### ISSUE THREAD

**Issue by RenaudF** [Rikiki123456789/Rimworld#2]
bullets just go through. Could be a similar problem as ED-Shields, see

https://github.com/jaxxa/ED-Shields-CR

**Comment by Rikiki123456789** [comment]
Hi RenaudF!

Sorry but I do not have enough time to maintain compatibility patches for CR.
My goal is to be compatible with the Vanilla game and as many mods as possible. CR however is a complete rework of a big part of the Core game and by the way it is no more actively developped.

If you want, propose a solution and I will look at it with interest. :-)

Rikiki
