### ISSUE TITLE
B18 attached

### ISSUE THREAD

**Issue by tommargar** [Rikiki123456789/Rimworld#9]
Hi Rikki, really missed Caveworld Flora so I updated it. Nothing else was touched, just made it work with B18.

Regards,
Killface
[CaveworldFlora.zip](https://github.com/Rikiki123456789/Rimworld/files/1514824/CaveworldFlora.zip)

**Comment by Rikiki123456789** [comment]
Thanks mate! :-)
It will be faster to update all my mods!
